#!/usr/bin/env python3
"""
generate_qadmus_roznama.py
Generate prayer_times.h and PTIMES.CSV for Al-Qadmus using the
Roznama-optimized method identified by comparing with the Roznama Android app.

Method  : Fajr=17.5°, Isha=17°, Maghrib+3min, Dhuhr+1min, Asr+1min
Location: Al-Qadmus, Tartus, Syria
Output  : prayer_times.h  (Arduino firmware fallback table)
          PTIMES.CSV       (SD card file — 365 lines, no header)

Run:
    python generate_qadmus_roznama.py
"""

import math
from datetime import datetime, timedelta
import ephem

# ---------------------------------------------------------------------------
# Configuration — edit only these values if needed
# ---------------------------------------------------------------------------
LAT  = 35.10138   # Al-Qadmus latitude  °N
LON  = 36.16111   # Al-Qadmus longitude °E
ELEV = 380        # elevation in metres
TZ   = 3          # Syria UTC+3 (year-round)

FAJR_ANGLE = '-17.5'   # degrees below horizon at Fajr
ISHA_ANGLE = '-17'     # degrees below horizon at Isha
MGH_ADJ    = 3         # minutes added to Maghrib (احتياط precautionary delay)
DHR_ADJ    = 1         # minutes added to Dhuhr
ASR_ADJ    = 1         # minutes added to Asr

YEAR = 2026            # non-leap year → 365 days Jan–Dec


# ---------------------------------------------------------------------------
# Astronomical calculations
# ---------------------------------------------------------------------------

def _obs(utc_dt):
    o = ephem.Observer()
    o.lat       = str(LAT)
    o.lon       = str(LON)
    o.elevation = ELEV
    o.date      = utc_dt
    return o


def _hm(utc_dt, offset_min=0):
    """Return (hour, minute) in local Syria time, with optional minute offset."""
    local = utc_dt + timedelta(hours=TZ, minutes=offset_min)
    return local.hour, local.minute


def _calc_asr_utc(utc_midnight):
    """Asr time via Shafi method (shadow = 1× object height). Returns UTC datetime."""
    obs = _obs(utc_midnight)
    sun = ephem.Sun()

    obs.horizon = '0'
    transit = obs.next_transit(sun)

    obs2 = _obs(transit.datetime())
    sun.compute(obs2)
    dec = float(sun.dec)   # radians
    lat = float(obs.lat)   # radians

    asr_alt = math.atan(1.0 / (1.0 + math.tan(abs(lat - dec))))
    cos_h = ((math.sin(asr_alt) - math.sin(lat) * math.sin(dec)) /
             (math.cos(lat) * math.cos(dec)))
    cos_h = max(-1.0, min(1.0, cos_h))
    h_hours = math.acos(cos_h) * 12.0 / math.pi

    return ephem.Date(float(transit) + h_hours * ephem.hour).datetime()


def calc_day(date):
    """
    Calculate prayer times for one date.
    Returns dict of prayer -> (hour, minute) in local Syria time.
    """
    utc_mid = datetime(date.year, date.month, date.day, 0, 0, 0)
    obs = _obs(utc_mid)
    sun = ephem.Sun()

    # Fajr
    obs.horizon = FAJR_ANGLE
    fajr = _hm(obs.next_rising(sun).datetime())

    # Dhuhr (+1 min convention: sun must have clearly passed zenith)
    obs.date    = utc_mid
    obs.horizon = '0'
    dhuhr = _hm(obs.next_transit(sun).datetime(), DHR_ADJ)

    # Asr (+1 min rounding convention)
    asr = _hm(_calc_asr_utc(utc_mid), ASR_ADJ)

    # Maghrib (sunset + احتياط)
    obs.date    = utc_mid
    obs.horizon = '0'
    maghrib_utc = obs.next_setting(sun).datetime()
    maghrib = _hm(maghrib_utc, MGH_ADJ)

    # Isha
    obs.date    = utc_mid
    obs.horizon = ISHA_ANGLE
    isha = _hm(obs.next_setting(sun).datetime())

    return {
        'fajr':    fajr,
        'dhuhr':   dhuhr,
        'asr':     asr,
        'maghrib': maghrib,
        'isha':    isha,
    }


# ---------------------------------------------------------------------------
# Output writers
# ---------------------------------------------------------------------------

HEADER_TOP = """\
#ifndef PRAYER_TIMES_H
#define PRAYER_TIMES_H

// Generated by generate_qadmus_roznama.py
// Location : Al-Qadmus, Tartus, Syria ({lat}N, {lon}E, elev ~{elev}m)
// Method   : Fajr={fajr}deg  Isha={isha}deg
//            Maghrib+{mgh}min  Dhuhr+{dhr}min  Asr+{asr}min
// Year ref : {year} (non-leap, 365 entries keyed by day+month)

typedef struct {{
  uint8_t day;
  uint8_t month;
  uint8_t fajr_hour;
  uint8_t fajr_min;
  uint8_t dhuhr_hour;
  uint8_t dhuhr_min;
  uint8_t asr_hour;
  uint8_t asr_min;
  uint8_t maghrib_hour;
  uint8_t maghrib_min;
  uint8_t isha_hour;
  uint8_t isha_min;
}} PrayerTime;

const PrayerTime prayer_times[365] = {{
"""

HEADER_BOTTOM = """\
}};

#endif // PRAYER_TIMES_H
"""


def write_header(rows, filename='prayer_times.h'):
    top = HEADER_TOP.format(
        lat=LAT, lon=LON, elev=ELEV,
        fajr=FAJR_ANGLE, isha=ISHA_ANGLE,
        mgh=MGH_ADJ, dhr=DHR_ADJ, asr=ASR_ADJ,
        year=YEAR,
    )
    lines = []
    for i, (d, m, t) in enumerate(rows):
        fh, fm = t['fajr']
        dh, dm = t['dhuhr']
        ah, am = t['asr']
        mh, mm = t['maghrib']
        ih, im = t['isha']
        comma = ',' if i < len(rows) - 1 else ''
        lines.append(
            f'  {{{d:2}, {m:2}, {fh}, {fm:2}, {dh}, {dm:2}, '
            f'{ah}, {am:2}, {mh}, {mm:2}, {ih}, {im:2}}}{comma}'
        )
    with open(filename, 'w', encoding='utf-8', newline='\n') as f:
        f.write(top)
        f.write('\n'.join(lines))
        f.write('\n')
        f.write(HEADER_BOTTOM)
    print(f'  [OK] {filename}  ({len(rows)} entries)')


def write_csv(rows, filename='PTIMES.CSV'):
    with open(filename, 'w', encoding='utf-8', newline='\n') as f:
        for d, m, t in rows:
            fh, fm = t['fajr']
            dh, dm = t['dhuhr']
            ah, am = t['asr']
            mh, mm = t['maghrib']
            ih, im = t['isha']
            f.write(f'{d},{m},{fh},{fm},{dh},{dm},{ah},{am},{mh},{mm},{ih},{im}\n')
    print(f'  [OK] {filename}  ({len(rows)} lines, no header)')


def print_sample(rows):
    prayers = ['Fajr', 'Dhuhr', 'Asr', 'Maghrib', 'Isha']
    keys    = ['fajr', 'dhuhr', 'asr', 'maghrib', 'isha']
    NW = 12
    print(f"  {'Date':<{NW}}" + ''.join(f'{p:>9}' for p in prayers))
    print('  ' + '-' * (NW + 9 * len(prayers)))
    sample_idx = [0, 1, 2, 90, 181, 272, 362, 363, 364]  # Jan, Apr, Jul, Oct, Dec
    for i in sample_idx:
        if i >= len(rows):
            continue
        d, m, t = rows[i]
        date_str = datetime(YEAR, m, d).strftime('%d %b')
        row = f'  {date_str:<{NW}}'
        for k in keys:
            h, mi = t[k]
            row += f'  {h:02d}:{mi:02d}  '
        print(row)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print('=' * 60)
    print('  Al-Qadmus Prayer Time Generator (Roznama-optimized)')
    print('=' * 60)
    print(f'  Location : {LAT}°N, {LON}°E, ~{ELEV}m')
    print(f'  Method   : Fajr={FAJR_ANGLE}°  Isha={ISHA_ANGLE}°')
    print(f'             Maghrib+{MGH_ADJ}min  Dhuhr+{DHR_ADJ}min  Asr+{ASR_ADJ}min')
    print(f'  Year ref : {YEAR}')
    print()

    rows = []
    date = datetime(YEAR, 1, 1)
    while date.year == YEAR:
        t = calc_day(date)
        rows.append((date.day, date.month, t))
        count = len(rows)
        if count % 30 == 0 or count == 1:
            print(f'  Computing... {count}/365', end='\r')
        date += timedelta(days=1)

    print(f'  Computing... 365/365 — done.         ')
    print()
    print('  Sample output (spot-check before using):')
    print_sample(rows)
    print()

    write_header(rows)
    write_csv(rows)

    print()
    print('  Next steps:')
    print('    1. Copy PTIMES.CSV to the ROOT of your FAT32 SD card')
    print('    2. Safely eject the card before removing it')
    print('    3. prayer_times.h is ready for the Arduino IDE')
    print('    4. Re-flash the firmware so the fallback table is also updated')


if __name__ == '__main__':
    main()
